version: '3.4'
 
networks:
    clinicareapp:       
        driver: bridge
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always #reinicia la base de datos automáticamente
        ports:
            - 1107:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=MyPass@word   
        networks:
            - clinicareapp
        volumes:
            - db-data:/var/opt/mssql          
    api:
        restart: unless-stopped #Reinicia excepto si yo lo paro de propio
        ports:
            - 7011:80
        build:
          context: .
          dockerfile: API/Dockerfile
        depends_on:
            - db
        networks:
            - clinicareapp
    web:
         image: carlota36/clinicare-vue:1.0
         ports:
             - 8082:80 
         depends_on:
             - api
        
volumes:
    db-data: {}
